---
title: "Navigating the Single-Cell Landscape: A Comprehensive Workshop on scRNAseq"
author: "CDN team"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    toc: true
    toc_float: true
    toc-location: left
    toc-depth: 4
    embed-resources: true
    self-contained-math: true
editor_options: 
  chunk_output_type: inline
---

## Day 1: March 18th 2024

-   **Where**: Center for Life Sciences 3 Rosen Conference Room
-   **Course Material**:
    -   [Download data from SCP/cellxgene](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/workshops/blob/main/navigating-the-single-cell-landscape-a-comprehensive-workshop-on-scrnaseq/day-1/1-cellxgene_census.html)
        -   Quick look into cellxgene platform
        -   Downloading data from SCP
    -   [How to compare clusters](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/workshops/blob/main/navigating-the-single-cell-landscape-a-comprehensive-workshop-on-scrnaseq/day-1/2-cluster-comparison.html)
        -   Statistical tests to obtain marker genes
        -   Statistics associated to each gene
        -   Visualization of marger genes
        -   Intepretation of the P-values
    -   [Clustering metrics](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/workshops/blob/main/navigating-the-single-cell-landscape-a-comprehensive-workshop-on-scrnaseq/day-1/3-clustering_metrics.html)
        -   Assessing sample-batch diversity
        -   Distances between clusters
    -   [Compositional analysis](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/workshops/blob/main/navigating-the-single-cell-landscape-a-comprehensive-workshop-on-scrnaseq/day-1/4-compositional_analysis.html)
        -   Brief overview on compositional data
        -   Using scCoda
        -   Workin on compositional space
    -   [Multi-condition Multi-sample differential expression](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/workshops/blob/main/navigating-the-single-cell-landscape-a-comprehensive-workshop-on-scrnaseq/day-1/5-multi-sample-multi-condition-DE.html)
        -   Pseudobulk DE analysis

## Day 2: March 25th 2024

-   **Where**: Center for Life Sciences 3 Rosen Conference Room
-   **Course Material**:
    -   [How to carry out factor analysis](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/workshops/blob/main/navigating-the-single-cell-landscape-a-comprehensive-workshop-on-scrnaseq/day-2/7-factor-analysis.html)
        -   How to determine the right number of K?
        -   Using UIK to identify the most relevant genes for each factor?
        -   Computing distances between and clustering factors
    -   [How to compute and interpret Gene signatures](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/workshops/blob/main/navigating-the-single-cell-landscape-a-comprehensive-workshop-on-scrnaseq/day-2/8-gene-signatures.html)
        -   Best practices on how to score gene signatures
        -   How to interpret these scores
        -   What genes are contributing to each signature
    -   [How to compute and interpret TF activities](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/workshops/blob/main/navigating-the-single-cell-landscape-a-comprehensive-workshop-on-scrnaseq/day-2/9-activity-scoring.html)
        -   Which databases to use
        -   Best practices on how to score them
        -   What genes are contributing to each TF activity
    -   [Intuition and limitations behind cell-cell communication analysis](http://htmlpreview.github.io/?https://github.com/CellDiscoveryNetwork/workshops/blob/main/navigating-the-single-cell-landscape-a-comprehensive-workshop-on-scrnaseq/day-2/6-CCC-analysis.html)
        -   State-of-the-art tools
        -   Visualization of the results
        -   Interpretation of the results

### Forms day-2

-   Please fill out this [form](https://forms.gle/Yd6WZsoKw9WfPLfc7) to track attendance.
-   Please take a moment to fill out the exit form for day 2 [here](https://docs.google.com/forms/d/e/1FAIpQLSdGDXb4dz0wV-qsBYo8Alqm010E-Y2V4aJ_8-VaSZa5NWOrCA/viewform?usp=sf_link). It really helps us plan better future workshops and improve the material of our current ones!
